export const CURRENT_DATE_REQUEST = 'CURRENT_DATE_REQUEST'
export const CURRENT_DATE_SUCCESS = 'CURRENT_DATE_SUCCESS'
export const CURRENT_DATE_FAIL = 'CURRENT_DATE_FAIL'

export const CURRENT_CITY_REQUEST = 'CURRENT_CITY_REQUEST'
export const CURRENT_CITY_SUCCESS = 'CURRENT_CITY_SUCCESS'
export const CURRENT_CITY_FAIL = 'CURRENT_CITY_FAIL'

export const OTHER_DATE_REQUEST = 'OTHER_DATE_REQUEST'
export const OTHER_DATE_SUCCESS = 'OTHER_DATE_SUCCESS'
export const OTHER_DATE_FAIL = 'OTHER_DATE_FAIL'